name: Debug

on:
  push:
    branches: [ develop, feature/*, bugfix/* ]
  pull_request:
    branches: [ develop, feature/*, bugfix/* ]

jobs:
  unix-build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'macos-latest']
        php-versions: ['8.0']
        phpunit-versions: ['latest']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, gd, pdo_sqlite
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug        
        tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --no-progress --no-suggest
    # - name: PHPUnit
    #   run: php ./vendor/bin/phpunit
    - name: Run Migration
      run: |
        export PHINX_ENVIRONMENT=testing
        cp -f configs/database.php.test configs/database.php
        php ./vendor/bin/phinx migrate
    - name: Run PHP CodeSniffer
      run: php ./vendor/bin/phpcs classes libraries error.php forgotpassword.php index.php multi_user.php register.php
  win-build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['windows-latest']
        php-versions: ['8.0']
        phpunit-versions: ['latest']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl, gd, pdo_sqlite
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: xdebug        
        tools: php-cs-fixer, phpunit:${{ matrix.phpunit-versions }}
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --no-progress --no-suggest
    - name: Run Migration
      run: |
        $Env:PHINX_ENVIRONMENT = "testing"
        Remove-Item configs/database.php
        Copy-Item configs/database.php.test configs/database.php
        php ./vendor/bin/phinx migrate
    - name: Run PHP CodeSniffer
      run: php ./vendor/bin/phpcs classes libraries error.php forgotpassword.php index.php multi_user.php register.php

